### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined when running accent synch --write (cli)

### ISSUE THREAD

**Issue by tom-wolters** [mirego/accent-cli#7]
When trying to sync a file I am getting an TypeError. 

`npm -v 5.5.1`
`accent-cli/0.4.0 darwin-x64 node-v8.9.1`

```
Fetch config... ✓
TypeError: Cannot read property 'find' of undefined at ConfigFetcher.operationConfig (/usr/local/lib/node_modules/accent-cli/lib/services/config.js:22:48) 

at ConfigFetcher.sync (/usr/local/lib/node_modules/accent-cli/lib/services/config.js:13:21)
at Sync.run (/usr/local/lib/node_modules/accent-cli/lib/commands/sync.js:17:46)
at Sync._run (/usr/local/lib/node_modules/accent-cli/node_modules/@oclif/command/lib/command.js:27:31)
at <anonymous>
```

**Comment by remiprev** [comment]
Hi! Can you paste the content of your `accent.json` file? Thank you!

**Comment by tom-wolters** [comment]
```
{
  "api": {
    "url": "http://ninetofive-accent.herokuapp.com",
    "key": "THEKEY"
  },
  "synch": [
    {
      "language": "nl",
      "format": "strings",
      "path": "Fietskluis/Utils/*.strings"
    }
  ]
}
```

**Comment by remiprev** [comment]
Looks like you have a typo, `synch` → `sync` 😉

**Comment by tom-wolters** [comment]
haha - I see... Many thanks.
